spring:
  application:
    name: base-spring-boot-architecture
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.ihsanakbay: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO

# JWT Configuration
jwt:
  secret: YourSecretKeyHereMakeItLongAndSecureInProductionEnvironment
  expiration: 86400000 # 24 hours in milliseconds
  
# Custom application properties
app:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Content-Type"
    max-age: 3600

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    use-root-path: true
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
  paths-to-match: /api/**
